import * as constants from './constants'
export const getInitListData = () => {
	let data = [
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					}
				]
	return{
		type:constants.GET_INIT_LIST_DATA,
		data
	}
}

export const switchFooterMenu = (data) => {
	return {
		type:constants.SWITCH_FOOTER_MENU,
		data
	}
}

export const switchTopMenu = (data) => {
	let a
	switch (data){
		case 0:
			a =[
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'微信客服:13056',
						description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'圆满资本',
						description:'昭阳区三元桥元岗中心b座1605',
						url:''
					},
					{
						headerImg:'',
						title:'中泰荣盛',
						description:'昭阳区建国门外东方瑞景2号楼1510',
						url:''
					},
					{
						headerImg:'',
						title:'首金担保',
						description:'昭阳区惠中北里310号楼2803室，1902室',
						url:''
					},
					{
						headerImg:'../../static/img/user01.jpg',
						title:'垫资-个人银装中泰荣盛',
						description:'',
						url:''
					}
				]
			break;
		case 1:
			a = [
						{
							headerImg:'../../static/img/user01.jpg',
							title:'车贷主题',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'车贷主题',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'微信客服:13056',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'圆满资本',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'微信客服:13056',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'圆满资本',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						}
					]
			break;
		case 2:
			a = [
						{
							headerImg:'../../static/img/user01.jpg',
							title:'信用主题',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'信用主题',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'微信客服:13056',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'圆满资本',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'微信客服:13056',
							description:'实名交友，非诚勿扰，未录入公司或信息有误联系客服，进入可扫二维码',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'圆满资本',
							description:'昭阳区三元桥元岗中心b座1605',
							url:''
						},
						{
							headerImg:'',
							title:'中泰荣盛',
							description:'昭阳区建国门外东方瑞景2号楼1510',
							url:''
						},
						{
							headerImg:'',
							title:'首金担保',
							description:'昭阳区惠中北里310号楼2803室，1902室',
							url:''
						},
						{
							headerImg:'../../static/img/user01.jpg',
							title:'垫资-个人银装中泰荣盛',
							description:'',
							url:''
						}
					]
			break;
		default:
			return;
	}
	return {
		type:constants.SWITCH_TOP_MENU_DATA,
		data:a
	}
}